---
title: "Matching Type"
subtitle: "Presenting a type of test"
author: "Group 3"
institute: "Technological University of the Philippines"
date: "May 25, 2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: 16:9
---
```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset()
```
# Definition

- an objective test consisting of two sets of items to be matched with each other for a specified attribute

--

- measures ability to identify relationship between a set of similar items

--

- recognition type and structured-response

--

- considered as modified multiple choice
---
# Parts of a Matching Type Test

Premises column is where the match **is located**

Responses column is where to **choose** a match
--
.pull-left[
### Column A (Premises)

1. Psychodynamic Theory

2. Trait Theory

3. Behaviorism

4. Humanism

]
--
.pull-right[
### Column B (Responses)

A. Sigmund Freud

B. Gordon Allport

C. B.F. Skinner

D. Carl Rogers
]
---
# Types of Matches
**Perfect Match** is when the number of items in premises and responses is **equal**

**Imperfect Match** is when the premises column **has less** items than premises column

--

.pull-left[
### Perfect Match
.pull-left[
1. Psychodynamic Theory

2. Trait Theory

3. Behaviorism

4. Humanism
]
.pull-right[
A. Sigmund Freud

B. Gordon Allport

C. B.F. Skinner

D. Carl Rogers
]
]

--

.pull-right[
### Imperfect Match
.pull-left[
1. Psychodynamic Theory

2. Trait Theory

3. Behaviorism

4. Humanism
]
.pull-right[
A. Sigmund Freud

B. Gordon Allport

C. B.F. Skinner

D. Carl Rogers

E. Albert Bandura
]
]

---
# Guidelines to Construction

1. Match the questions to your objectives

--

2. Give clear instructions

--

3. Use numbers for column A, capital letters for column B

--

4. Use imperfect match

--

5. Arrange column B in logical order

--

6. Put more words in column A

--

7. Keep two sets homogenous

--

8. Avoid using pattern

--

9. Avoid copying statements from textbooks
---
# Examples to follow the Guidelines

.panelset[

.panel[.panel-name[Match Objectives]
.pull-left[
They are effective when you need to measure the learner’s ability to identify the relationship. 

Measures the ability to solve:

- Terms and Definition

- Relate pictures to labels

- Causes and Effects

- Scenarios and Responses
]
.pull-right[
Objective: Students will **match** the educational perspective to their proponent.

Test Item:
Given a list of names and educational perspectives. Match the two columns properly. 

The objective of the lesson is designed to create a Matching Type Test
]

]

.panel[.panel-name[Create Test]
.pull-left[
Instructions: Write the letter of your answer before the number. No items may be used more than once.
.pull-left[
### Column A
1. Psychodynamic Theory

2. Trait Theory

3. Behaviorism

4. Humanism

5. Social Learning Theory
]
.pull-right[
### Column B
A. Albert Bandura

B. B.F. Skinner

C. Carl Jung

D. Carl Rogers

E. Gordon Allport

F. Sigmund Freud

]
]

.pull-right[
&#10003; has a clear instruction

&#10003; homogenous

&#10003; one correct answer

&#10003; unequal responses

&#10003; answers do not follow a pattern

&#10003; questions are limited to 5-15 items
]

]

.panel[.panel-name[Have Key]
### Key to Correction

1. F

2. E

3. B

4. D

5. A

]
]
---
# Your turn

Instructions: 

Identify the statements if it is a **advantage of using** a Matching Type Test

Type **1** if the statement is a advantage of Matching Type Tests

Type **0** if the statement is not a advantage of Matching Type Tests

Use the chatbox. All students are required to response 
---
# Questions
1. Encourage cheating

--
0

2. Scoring is not subjective

--
1

3. Covers more content

--
1

4. Students can guess in this type of exam 

--
0

5. Allows comparison of related ideas

--
1

6. There are certain subjects that objective examinations do not work

--
0

7. Limits the assessment to lower levels of understanding

--
0
---
# Questions

8\. Measures factual knowledge only

--
0

9\. Provide objective measurement of student knowledge

--
1

10\. Validity and reliablity is higher than essays

--
1

11\. Saves time in answering questions

--
1

12\. Requires more preparation for teachers

--
0

13\. Does not express the ideas of your students

--
0

14\. Easy to check

--
1
---
.pull-left[
### Advantages
- Validity and reliablity is higher than essays

- Covers more content

- Provide objective measurement of student knowledge

- Easy to check

- Allows comparison of related ideas

- Scoring is not subjective

- Saves time in answering questions
]
.pull-right[
### Disadvantages
- Limits the assessment to lower levels of understanding

- Measures factual knowledge only

- Students can guess in this type of exam

- There are certain subjects that objective examinations do not work

- Encourage cheating

- Requires more preparation for teachers

- Does not express the ideas of your students
]
---
# Resources

Matching type. (2014). Slideshare.net. https://www.slideshare.net/1enchantress/matching-type-37879883?fbclid=IwAR15whq8q3JbaUv1tVGLzuMaX3BTmDHDx94aVC75WI7XJh5a7K4XoTMimVg

Malamed, C. (2010, July 20). Tips For Writing Matching Format Test Items. The ELearning Coach. https://theelearningcoach.com/elearning_design/writing-matching-test-items/

Vincent de Ocampo. (2016). Matching type of evaluation. Slideshare.net. https://www.slideshare.net/vbdeocampo/matching-type-of-evaluation